version: '3.9'

services:
  
  php:
    container_name: pdv_app_php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network
    depends_on:
      - db

  web:
    container_name: pdv_app_web
    build:
      context: ./docker/apache
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php
    networks:
      - app-network
  
  db:
    container_name: pdv_app_db
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE=pdv_app
      - MYSQL_USER=pdv_app
      - MYSQL_PASSWORD=pdv_app
      - MYSQL_ROOT_PASSWORD=pdv_app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
 
networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  